spring:
  profile:
    active: dev
  application:
    name: s3-to-postgres
  datasource:
    url: "jdbc:postgresql://<<DB Endpoint>>:<<portnumber>>/<<Database Name>>"     #Postgres DB JDBC URL
    username: "master-username"                                                   #Postgres DB Username
    password: "master-password"                                                   #Postgres DB Password
    hikari:
      maximumPoolSize: 5                                                          #Postgres DB Connection Pool size

server:
  port: 7070
  servlet:
    context-path: /s3-to-postgres

s3topostgres:
  sqs:
    notification:
      queue: <<SQS Queue Name>>
  db:
    query: COPY employees (employee_id, first_name, last_name, title, email) FROM STDIN (FORMAT CSV)

logging:
  file: /home/ec2-user/s3-to-postgres/s3-to-postgres.log
  level:
    com.sandeep.learning.s3topostgres: DEBUG
    org.springframework.web: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [thread] %-5level %logger{36} - %msg%n"

# Spring Cloud AWS tries to auto configure CloudFormation (when the app runs in EC2).
# To disable set cloud.aws.stack.auto=false
cloud:
  aws:
    stack:
      auto: false